version: 2
updates:
  # =====================================================
  # NPM DEPENDENCIES
  # =====================================================
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 10
    reviewers:
      - 'joels'
    assignees:
      - 'joels'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'javascript'
    ignore:
      # Ignorar actualizaciones de versiones mayores para dependencias críticas
      - dependency-name: 'next'
        update-types: ['version-update:semver-major']
      - dependency-name: 'react'
        update-types: ['version-update:semver-major']
      - dependency-name: 'react-dom'
        update-types: ['version-update:semver-major']
      - dependency-name: '@supabase/supabase-js'
        update-types: ['version-update:semver-major']

  # =====================================================
  # GITHUB ACTIONS
  # =====================================================
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '09:00'
    open-pull-requests-limit: 5
    reviewers:
      - 'joels'
    assignees:
      - 'joels'
    commit-message:
      prefix: 'ci'
      include: 'scope'
    labels:
      - 'dependencies'
      - 'github-actions'
